server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:myservice.p12
    key-store-type: PKCS12
    key-store-password: password

spring:
  application:
    name: file-uploader
  kafka:
    bootstrap-servers: localhost:9092
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

feign:
  file-status-processor:
    url: localhost:8083/status
