spring:
  application:
    name: file-uploader
  kafka:
    bootstrap-servers: localhost:9092
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

feign:
  file-status-processor:
    url: http://localhost:8083/status
